# Generated by Django 4.2.19 on 2026-05-13 18:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizational_structure', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='When the work begins')),
                ('end_date', models.DateField(help_text='When the work must be completed')),
                ('industry_mentor', models.CharField(blank=True, help_text='The industry person supervising the task', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry_type', models.CharField(choices=[('it', 'IT'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('industry_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone format', regex='^\\+?[0-9\\-\\s\\(\\)]{9,25}$')])),
                ('contact_person_phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone format', regex='^\\+?[0-9\\-\\s\\(\\)]{9,25}$')])),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requesting_entity', models.CharField(choices=[('industry', 'Industry'), ('academic_unit', 'Academic Unit'), ('staff', 'Staff'), ('student', 'Student')], max_length=20)),
                ('type', models.CharField(choices=[('rnd', 'Research & Development Services'), ('tech_support', 'Technology Support'), ('consultancy', 'Consultancy'), ('testing', 'Testing & QA'), ('training', 'Training'), ('internship', 'Internship/Externship'), ('externship', 'Externship'), ('recruitment', 'Graduate Recruitment'), ('curriculum_review', 'Curriculum Review'), ('industrial_visit', 'Industrial Visit'), ('joint_research', 'Joint Research'), ('guest_lecture', 'Guest Lecturing'), ('lab_access', 'Equipment / Lab Access'), ('tech_transfer', 'IP / Technology Transfer'), ('workshop_call', 'Workshop Call'), ('conference_call', 'Conference Call'), ('exhibition_call', 'Exhibition Call'), ('joint_community_engagement', 'Joint Community Engagement'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='request_attachments/')),
                ('academic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='organizational_structure.organizationalunit')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='industry_linkage.industry')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('accept_forwarded', 'Accept Forwarded'), ('replied', 'Replied'), ('reverted', 'Reverted'), ('promoted_to_project', 'Promoted to Project')], max_length=30)),
                ('description', models.TextField()),
                ('awaiting_decision', models.BooleanField(default=False)),
                ('resulted_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('from_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('to_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('from_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_sent', to='contenttypes.contenttype')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='industry_linkage.request')),
                ('resulted_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestaction_resulted', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_received', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Request Action',
                'verbose_name_plural': 'Request Actions',
            },
        ),
        migrations.CreateModel(
            name='AssignmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pi', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='industry_linkage.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'user')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assignments', through='industry_linkage.AssignmentMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='industry_linkage.request'),
        ),
    ]
