# Generated by Django 4.2.19 on 2026-05-01 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizational_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('industry_type', models.CharField(choices=[('it', 'IT'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('industry_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requesting_entity', models.CharField(choices=[('industry', 'Industry'), ('academic_unit', 'Academic Unit')], max_length=20)),
                ('type', models.CharField(choices=[('rnd', 'Research & Development  Services'), ('tech_support', 'Technology Support'), ('consultancy', 'Consultancy'), ('testing', 'Testing & QA'), ('training', 'Training'), ('internship', 'Internship/Externship'), ('recruitment', 'Graduate Recruitment'), ('curriculum_review', 'Curriculum Review'), ('industrial_visit', 'Industrial Visit'), ('joint_research', 'Joint Research'), ('guest_lecture', 'Guest Lecturing'), ('lab_access', 'Equipment / Lab Access'), ('tech_transfer', 'IP / Technology Transfer'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='request_attachments/')),
                ('academic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='organizational_structure.organizationalunit')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='industry_linkage.industry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_trainees', models.PositiveIntegerField()),
                ('trainee_level', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='TestingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_to_test', models.CharField(max_length=255)),
                ('test_type', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testing', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='TechTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_description', models.TextField()),
                ('technology_readiness_level', models.CharField(max_length=50)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_transfer', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologySupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_required', models.CharField(blank=True, max_length=255, null=True)),
                ('required_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_support', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='RnDRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('research_area', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rnd', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pi', 'Principal Investigator'), ('member', 'Member')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='industry_linkage.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('accept_forwarded', 'Accept Forwarded'), ('replied', 'Replied')], max_length=30)),
                ('description', models.TextField()),
                ('forwarded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_forwards', to='organizational_structure.organizationalunit')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_forwards', to='organizational_structure.organizationalunit')),
                ('from_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='industry_linkage.industry')),
                ('from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='organizational_structure.organizationalunit')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='industry_linkage.request')),
                ('to_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='industry_linkage.industry')),
                ('to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='organizational_structure.organizationalunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_year', models.IntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('number_to_recruit', models.PositiveIntegerField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='JointResearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_topic', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('expected_industry_contribution', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joint_research', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=255)),
                ('number_of_students', models.PositiveIntegerField()),
                ('timeframe', models.CharField(max_length=100)),
                ('activities', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.PositiveIntegerField()),
                ('preferred_datetime', models.DateTimeField()),
                ('department_to_visit', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_visit', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='GuestLectureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('student_level', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_lecture', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('current_syllabus', models.FileField(upload_to='syllabus/')),
                ('desired_industry_expertise', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_review', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancy_type', models.CharField(blank=True, max_length=255, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy', to='industry_linkage.request')),
            ],
        ),
    ]
