# Generated by Django 4.2.19 on 2026-04-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizational_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry_type', models.CharField(choices=[('it', 'IT'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('industry_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rnd', 'Research & Development  Services'), ('tech_support', 'Technology Support'), ('consultancy', 'Consultancy'), ('testing', 'Testing & QA'), ('training', 'Training'), ('internship', 'Internship/Externship'), ('recruitment', 'Graduate Recruitment'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='request_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_trainees', models.PositiveIntegerField()),
                ('trainee_level', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='industry_linkage.industryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologySupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_required', models.CharField(blank=True, max_length=255, null=True)),
                ('required_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_support', to='industry_linkage.industryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pi', 'Principal Investigator'), ('member', 'Member')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='industry_linkage.industryrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_year', models.IntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('number_to_recruit', models.PositiveIntegerField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='industry_linkage.industryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryRequestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('replied', 'Replied')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_forwards', to='organizational_structure.organizationalunit')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_forwards', to='organizational_structure.organizationalunit')),
                ('from_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='industry_linkage.industry')),
                ('from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='organizational_structure.organizationalunit')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='industry_linkage.industryrequest')),
                ('to_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='industry_linkage.industry')),
                ('to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='organizational_structure.organizationalunit')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancy_type', models.CharField(blank=True, max_length=255, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy', to='industry_linkage.industryrequest')),
            ],
        ),
    ]
