# Generated by Django 4.2.19 on 2026-05-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='visbil_to_industry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='academic_unit_name',
            field=models.CharField(blank=True, help_text='Used when the exact academic unit is unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
