# Generated by Django 4.2.19 on 2026-05-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
