# Generated by Django 4.2.19 on 2026-04-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
