# Generated by Django 4.2.19 on 2026-04-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industryrequestaction',
            old_name='action_type',
            new_name='type',
        ),
    ]
