# Generated by Django 4.2.19 on 2026-05-01 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0002_alter_industry_industry_email_alter_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone format', regex='^\\+?[0-9\\-\\s\\(\\)]{9,25}$')]),
        ),
        migrations.AlterField(
            model_name='industry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone format', regex='^\\+?[0-9\\-\\s\\(\\)]{9,25}$')]),
        ),
    ]
