# Generated by Django 4.2.19 on 2026-05-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0002_assignment_visbil_to_industry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='visbil_to_industry',
            new_name='visible_to_industry',
        ),
    ]
