# Generated by Django 4.2.19 on 2026-04-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_structure', '0001_initial'),
        ('industry_linkage', '0003_industry_created_by_industry_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryrequest',
            name='requested_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_requests', to='organizational_structure.organizationalunit'),
        ),
    ]
