# Generated by Django 4.2.19 on 2026-05-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_structure', '0001_initial'),
        ('industry_linkage', '0003_rename_visbil_to_industry_assignment_visible_to_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='academic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='organizational_structure.organizationalunit'),
        ),
    ]
