# Generated by Django 4.2.19 on 2026-05-02 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizational_structure', '0001_initial'),
        ('industry_linkage', '0003_alter_industry_contact_person_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='When the work begins')),
                ('end_date', models.DateField(help_text='When the work must be completed')),
                ('industry_mentor', models.CharField(blank=True, help_text='The industry person supervising the task', max_length=255, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_assignments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='industry_linkage.request')),
            ],
            options={
                'unique_together': {('request', 'assigned_user')},
            },
        ),
        migrations.RemoveField(
            model_name='requestaction',
            name='forwarded_from',
        ),
        migrations.RemoveField(
            model_name='requestaction',
            name='forwarded_to',
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='from_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_unit_transfers', to='organizational_structure.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='to_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers_industry', to='industry_linkage.industry'),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='to_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_unit_transfers', to='organizational_structure.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('accept_forwarded', 'Accept Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('replied', 'Replied'), ('reject', 'Rejected'), ('reassigned', 'Reassigned'), ('completed', 'Completed')], max_length=30),
        ),
        migrations.DeleteModel(
            name='RequestAssignment',
        ),
    ]
