# Generated by Django 4.2.19 on 2026-04-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_structure', '0001_initial'),
        ('industry_linkage', '0004_industryrequest_requested_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryrequest',
            name='requested_to',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='industry_requests', to='organizational_structure.organizationalunit'),
            preserve_default=False,
        ),
    ]
