# Generated by Django 4.2.19 on 2026-05-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0004_assignment_remove_requestaction_forwarded_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestaction',
            name='performed_by',
        ),
    ]
