# Generated by Django 4.2.19 on 2026-05-02 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('industry_linkage', '0005_remove_requestaction_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestaction',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignends', to=settings.AUTH_USER_MODEL),
        ),
    ]
