# Generated by Django 4.2.19 on 2026-04-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0005_alter_industryrequest_requested_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_to_test', models.CharField(max_length=255)),
                ('test_type', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testing', to='industry_linkage.industryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RnDRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('research_area', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rnd', to='industry_linkage.industryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=255)),
                ('number_of_students', models.PositiveIntegerField()),
                ('timeframe', models.CharField(max_length=100)),
                ('activities', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='industry_linkage.industryrequest')),
            ],
        ),
    ]
