# Generated by Django 4.2.19 on 2026-05-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0006_requestaction_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaction',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('accept_forwarded', 'Accept Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('replied', 'Replied'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('revoked', 'Revoked')], max_length=30),
        ),
    ]
