# Generated by Django 4.2.19 on 2026-05-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0007_alter_requestaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumreviewrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='guestlecturerequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='industrialvisitrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='internshiprequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='jointresearchrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='recruitmentrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='rndrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='technologysupportrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='techtransferrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='testingrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='trainingrequest',
            name='request',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('accept_forwarded', 'Accept Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('replied', 'Replied'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('revoked', 'Revoked'), ('canceled', 'Cancelled')], max_length=30),
        ),
        migrations.DeleteModel(
            name='ConsultancyRequest',
        ),
        migrations.DeleteModel(
            name='CurriculumReviewRequest',
        ),
        migrations.DeleteModel(
            name='GuestLectureRequest',
        ),
        migrations.DeleteModel(
            name='IndustrialVisitRequest',
        ),
        migrations.DeleteModel(
            name='InternshipRequest',
        ),
        migrations.DeleteModel(
            name='JointResearchRequest',
        ),
        migrations.DeleteModel(
            name='RecruitmentRequest',
        ),
        migrations.DeleteModel(
            name='RnDRequest',
        ),
        migrations.DeleteModel(
            name='TechnologySupportRequest',
        ),
        migrations.DeleteModel(
            name='TechTransferRequest',
        ),
        migrations.DeleteModel(
            name='TestingRequest',
        ),
        migrations.DeleteModel(
            name='TrainingRequest',
        ),
    ]
