# Generated by Django 4.2.19 on 2026-05-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0008_remove_curriculumreviewrequest_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('accept_forwarded', 'Accept Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('replied', 'Replied'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('revoked', 'Revoked')], max_length=30),
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_trainees', models.PositiveIntegerField()),
                ('trainee_level', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='TestingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_to_test', models.CharField(max_length=255)),
                ('test_type', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testing', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='TechTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_description', models.TextField()),
                ('technology_readiness_level', models.CharField(max_length=50)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_transfer', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologySupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_required', models.CharField(blank=True, max_length=255, null=True)),
                ('required_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_support', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='RnDRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('research_area', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rnd', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_year', models.IntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('number_to_recruit', models.PositiveIntegerField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='JointResearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_topic', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('expected_industry_contribution', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joint_research', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=255)),
                ('number_of_students', models.PositiveIntegerField()),
                ('timeframe', models.CharField(max_length=100)),
                ('activities', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.PositiveIntegerField()),
                ('preferred_datetime', models.DateTimeField()),
                ('department_to_visit', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_visit', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='GuestLectureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('student_level', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_lecture', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('current_syllabus', models.FileField(upload_to='syllabus/')),
                ('desired_industry_expertise', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_review', to='industry_linkage.request')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancy_type', models.CharField(blank=True, max_length=255, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy', to='industry_linkage.request')),
            ],
        ),
    ]
