# Generated by Django 4.2.19 on 2026-05-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('industry_linkage', '0010_remove_curriculumreviewrequest_request_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestaction',
            options={'verbose_name': 'Request Action', 'verbose_name_plural': 'Request Actions'},
        ),
        migrations.RemoveField(
            model_name='requestaction',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='requestaction',
            name='from_industry',
        ),
        migrations.RemoveField(
            model_name='requestaction',
            name='from_unit',
        ),
        migrations.RemoveField(
            model_name='requestaction',
            name='to_industry',
        ),
        migrations.RemoveField(
            model_name='requestaction',
            name='to_unit',
        ),
        migrations.AddField(
            model_name='requestaction',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industry_linkage.assignment'),
        ),
        migrations.AddField(
            model_name='requestaction',
            name='from_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_sent', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='requestaction',
            name='from_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestaction',
            name='to_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_received', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='requestaction',
            name='to_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('rnd', 'Research & Development  Services'), ('tech_support', 'Technology Support'), ('consultancy', 'Consultancy'), ('testing', 'Testing & QA'), ('training', 'Training'), ('internship', 'Internship/Externship'), ('recruitment', 'Graduate Recruitment'), ('curriculum_review', 'Curriculum Review'), ('industrial_visit', 'Industrial Visit'), ('joint_research', 'Joint Research'), ('guest_lecture', 'Guest Lecturing'), ('lab_access', 'Equipment / Lab Access'), ('tech_transfer', 'IP / Technology Transfer'), ('workshop_call', 'Workshop Call'), ('conference _call', 'Conference  Call'), ('exhibition_call', 'Exhibition Call'), ('joint_ommunity_engagement', 'Joint Community engagement'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='type',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('accept_forwarded', 'Accept Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('replied', 'Replied'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('revoked', 'Revoked'), ('canceled', 'Cancelled'), ('revert', 'Revert')], max_length=30),
        ),
    ]
