# Generated by Django 4.2.19 on 2026-05-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('industry_linkage', '0011_alter_requestaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestaction',
            name='assignment',
        ),
        migrations.AddField(
            model_name='requestaction',
            name='resulted_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestaction_resulted', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='requestaction',
            name='resulted_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='type',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('revoked', 'Revoked'), ('cancelled', 'Cancelled'), ('accept_forwarded', 'Accept Forwarded'), ('replied', 'Replied'), ('revert', 'Revert')], max_length=30),
        ),
    ]
