# Generated by Django 4.2.19 on 2026-05-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0012_remove_requestaction_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestaction',
            name='is_active',
        ),
        migrations.AddField(
            model_name='requestaction',
            name='awaiting_decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='requesting_entity',
            field=models.CharField(choices=[('industry', 'Industry'), ('academic_unit', 'Academic Unit'), ('staff', 'Staff'), ('student', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('rnd', 'Research & Development Services'), ('tech_support', 'Technology Support'), ('consultancy', 'Consultancy'), ('testing', 'Testing & QA'), ('training', 'Training'), ('internship', 'Internship/Externship'), ('recruitment', 'Graduate Recruitment'), ('curriculum_review', 'Curriculum Review'), ('industrial_visit', 'Industrial Visit'), ('joint_research', 'Joint Research'), ('guest_lecture', 'Guest Lecturing'), ('lab_access', 'Equipment / Lab Access'), ('tech_transfer', 'IP / Technology Transfer'), ('workshop_call', 'Workshop Call'), ('conference_call', 'Conference Call'), ('exhibition_call', 'Exhibition Call'), ('joint_community_engagement', 'Joint Community Engagement'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='type',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('revoked', 'Revoked'), ('cancelled', 'Cancelled'), ('accept_forwarded', 'Accept Forwarded'), ('replied', 'Replied'), ('reverted', 'Reverted')], max_length=30),
        ),
    ]
