# Generated by Django 4.2.19 on 2026-05-06 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('industry_linkage', '0013_remove_requestaction_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_user',
        ),
    ]
