# Generated by Django 4.2.19 on 2026-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_linkage', '0014_alter_assignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaction',
            name='type',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('forwarded', 'Forwarded'), ('posted_as_thematic', 'Posted as Thematic Call'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('accept_forwarded', 'Accept Forwarded'), ('replied', 'Replied'), ('reverted', 'Reverted')], max_length=30),
        ),
    ]
