services:
  backend:
    build:
      context: ./iuls_backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./iuls_backend/.env
    develop:
      watch:
        - action: sync
          path: ./iuls_backend
          target: /app
          ignore:
            - venv/
            - __pycache__/
            - .git/
        - action: rebuild
          path: ./iuls_backend/requirements.txt

  alembic:
    build:
      context: ./iuls_backend
      dockerfile: Dockerfile
    container_name: alembic_runner
    command: alembic upgrade head
    volumes:
      - ./iuls_backend:/app
    env_file:
      - ./iuls_backend/.env
    depends_on:
      - db
    restart: "no"             

  frontend:
    build:
      context: ./uil_frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./uil_frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/
        - action: rebuild
          path: ./uil_frontend/package.json

  db:
    container_name: fastapi_db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: iuls
      POSTGRES_USER: root
      POSTGRES_PASSWORD: disSAMI!123
    ports:
      - "5432:5432"

volumes:
  postgres_data:
