services:
  backend:
    build: ./uil_backend
    container_name: uil_backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    env_file:
      - ./uil_backend/.env.backend.dev

    volumes:
      - ./uil_backend/accounts/migrations:/app/accounts/migrations
      - ./uil_backend/authorization/migrations:/app/authorization/migrations
      - ./uil_backend/organizational_structure/migrations:/app/organizational_structure/migrations
      - ./uil_backend/industry_linkage/migrations:/app/industry_linkage/migrations

      - ./uil_backend/media:/app/media
    develop:
      watch:
        - action: sync
          path: ./uil_backend
          target: /app
        - action: rebuild
          path: ./uil_backend/requirements.txt
        - action: rebuild
          path: ./uil_backend/gunicorn_config.py
        - action: rebuild
          path: ./uil_backend/manage.py
        - action: sync
          path: ./uil_backend/entrypoint.sh
          target: /app/entrypoint.sh

  mysql_db:
    image: mysql:8.0
    container_name: uil_db
    env_file:
      - ./uil_backend/.env.backend.dev
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./uil_frontend
      dockerfile: Dockerfile
    container_name: uil_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./uil_frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/
        - action: rebuild
          path: ./uil_frontend/package.json

volumes:
  mysql_data:
