"""relation shipt between profile and academinc unit 

Revision ID: 4945e773143a
Revises: eb3354f39d72
Create Date: 2026-04-04 21:51:59.218266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4945e773143a'
down_revision: Union[str, Sequence[str], None] = 'eb3354f39d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_profile', sa.Column('academic_unit_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'staff_profile', 'organizational_unit', ['academic_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_profile', type_='foreignkey')
    op.drop_column('staff_profile', 'academic_unit_id')
    # ### end Alembic commands ###
