"""initial

Revision ID: 8edbfbe0d783
Revises: 
Create Date: 2026-04-04 20:22:38.500962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edbfbe0d783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry', sa.Column('account_id', sa.String(), nullable=False))
    op.add_column('industry', sa.Column('status', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'industry', ['account_id'])
    op.create_foreign_key(None, 'industry', 'account', ['account_id'], ['id'])
    op.drop_column('industry', 'email')
    op.drop_constraint(op.f('organizational_unit_created_by_id_fkey'), 'organizational_unit', type_='foreignkey')
    op.drop_constraint(op.f('organizational_unit_updated_by_id_fkey'), 'organizational_unit', type_='foreignkey')
    op.drop_column('organizational_unit', 'created_by_id')
    op.drop_column('organizational_unit', 'updated_by_id')
    op.add_column('user', sa.Column('account_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['account_id'])
    op.create_foreign_key(None, 'user', 'account', ['account_id'], ['id'])
    op.drop_column('user', 'email')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'account_id')
    op.add_column('organizational_unit', sa.Column('updated_by_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizational_unit', sa.Column('created_by_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('organizational_unit_updated_by_id_fkey'), 'organizational_unit', 'user', ['updated_by_id'], ['id'])
    op.create_foreign_key(op.f('organizational_unit_created_by_id_fkey'), 'organizational_unit', 'user', ['created_by_id'], ['id'])
    op.add_column('industry', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'industry', type_='foreignkey')
    op.drop_constraint(None, 'industry', type_='unique')
    op.drop_column('industry', 'status')
    op.drop_column('industry', 'account_id')
    # ### end Alembic commands ###
