"""renaming user to staff problem

Revision ID: eb3354f39d72
Revises: 8edbfbe0d783
Create Date: 2026-04-04 21:36:30.297232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb3354f39d72'
down_revision: Union[str, Sequence[str], None] = '8edbfbe0d783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE "user" CASCADE;')
    op.alter_column('assignment', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('assignment_staff_id_fkey', 'assignment', type_='foreignkey', if_exists=True)
    op.create_foreign_key(None, 'assignment', 'staff_profile', ['staff_id'], ['id'])
    op.alter_column('industry', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('industry_request', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('notification_target_user_id_fkey'), 'notification', type_='foreignkey', if_exists=True)
    op.drop_constraint(op.f('staff_profile_academic_unit_id_fkey'), 'staff_profile', type_='foreignkey', if_exists=True)
    op.create_foreign_key(None, 'notification', 'account', ['target_user_id'], ['id'])
    op.alter_column('post', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('staff_profile', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('staff_profile', 'academic_unit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_profile', sa.Column('academic_unit_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('staff_profile_academic_unit_id_fkey'), 'staff_profile', 'organizational_unit', ['academic_unit_id'], ['id'])
    op.alter_column('staff_profile', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_target_user_id_fkey'), 'notification', 'user', ['target_user_id'], ['id'])
    op.alter_column('industry_request', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('industry', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_staff_id_fkey'), 'assignment', 'user', ['staff_id'], ['id'])
    op.alter_column('assignment', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('father_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grand_father_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('must_change_password', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('research_interests', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publication_isced_band', postgresql.ENUM('GENERIC', 'EDUCATION', 'ARTS_HUMANITIES', 'SOCIAL_SCIENCES', 'BUSINESS_LAW', 'NATURAL_SCIENCES', 'ICT', 'ENGINEERING', 'AGRICULTURE', 'HEALTH_WELFARE', 'SERVICES', 'FIELD_UNKNOWN', name='iscedbandcode'), autoincrement=False, nullable=True),
    sa.Column('author_category', postgresql.ENUM('ACADEMIC_STAFF', 'FIRST_DEGREE_STUDENT', 'SECOND_DEGREE_STUDENT', 'THIRD_DEGREE_STUDENT', 'FULL_TIME_RESEARCHER', name='authorcategorycode'), autoincrement=False, nullable=True),
    sa.Column('author_academic_rank', postgresql.ENUM('GRAD_ASSISTANT_I', 'GRAD_ASSISTANT_II', 'LECTURER', 'ASSISTANT_PROFESSOR', 'ASSOCIATE_PROFESSOR', 'PROFESSOR', 'ASSISTANT_LECTURER', 'TECHNICAL_ASSISTANCE', name='academicrankcode'), autoincrement=False, nullable=True),
    sa.Column('author_qualification', postgresql.ENUM('BACHELOR', 'HEALTH_SPECIALITY', 'POST_GRAD_DIPLOMA', 'MASTER', 'DOCTORATE', 'HEALTH_SUB_SPECIALTY', 'BACHELOR_TEACHING', name='qualificationcode'), autoincrement=False, nullable=True),
    sa.Column('author_employment_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'JOINT_EDU', 'JOINT_INDUSTRY', 'VISITING_PROFESSOR', name='employmenttypecode'), autoincrement=False, nullable=True),
    sa.Column('academic_title', postgresql.ENUM('MR', 'MRS', 'MISS', 'MS', 'DR', 'PROF', name='academictitle'), autoincrement=False, nullable=True),
    sa.Column('academic_unit_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['organizational_unit.id'], name=op.f('user_academic_unit_id_fkey')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('user_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('account_id', name=op.f('user_account_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
