"""Add new fields

Revision ID: 87ca97a7822b
Revises: 
Create Date: 2026-03-30 13:27:51.034307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ca97a7822b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('academic_unit_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('user_department_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'organizational_unit', ['academic_unit_id'], ['id'])
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_department_id_fkey'), 'user', 'organizational_unit', ['department_id'], ['id'])
    op.drop_column('user', 'academic_unit_id')
    # ### end Alembic commands ###
