from authorization.constants import (
    CAN_CREATE_INDUSTRY,
    CAN_CREATE_INDUSTRY_REQUEST,
    CAN_READ_INDUSTRY__REQUEST_DETAIL,
    CAN_READ_INDUSTRY_LIST,
    CAN_DELETE_INDUSTRY,
    CAN_DELETE_INDUSTRY_REQUEST,
    CAN_READ_INDUSTRY__REQUEST_LIST,
    CAN_READ_INDUSTRY_DETAIL,
    CAN_UPDATE_INDUSTRY,
    CAN_UPDATE_INDUSTRY_REQUEST,
    
)



INDUSTRY_REQUIRED_PERMISSIONS={
    'list': [CAN_READ_INDUSTRY_LIST],
    'retrieve': [CAN_READ_INDUSTRY_DETAIL],
    'destroy': [CAN_DELETE_INDUSTRY],
    'update': [CAN_UPDATE_INDUSTRY],
    'partial_update': [CAN_UPDATE_INDUSTRY],
    'create': [],
}

INDUSTRY_REQUEST_REQUIRED_PERMISSIONS={
    'list': [CAN_READ_INDUSTRY__REQUEST_LIST],
    'retrieve': [CAN_READ_INDUSTRY__REQUEST_DETAIL],
    'destroy': [CAN_DELETE_INDUSTRY_REQUEST],
    'update': [CAN_UPDATE_INDUSTRY_REQUEST],
    'partial_update': [CAN_UPDATE_INDUSTRY_REQUEST],
    'create': [CAN_CREATE_INDUSTRY_REQUEST],

}