# Generated by Django 4.2.19 on 2026-04-16 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_type', models.CharField(choices=[('university', 'University'), ('campus', 'Campus'), ('college', 'College'), ('institute', 'Institute'), ('faculty', 'Faculty'), ('school', 'School'), ('department', 'Department'), ('academy', 'Academy'), ('research_center', 'Research Center'), ('support_unit', 'Support Unit'), ('program', 'Program'), ('office', 'Office'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_organization_structures', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnodes', to='organizational_structure.organizationalunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_organization_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Structure',
                'verbose_name_plural': 'Organization Structures',
                'ordering': ['unit_type', 'name'],
                'unique_together': {('name', 'parent')},
            },
        ),
    ]
