# Generated by Django 4.2.19 on 2026-05-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('post_type', models.CharField(choices=[('success_story', 'Success Story'), ('thematic_area', 'Thematic Area'), ('open_request', 'Open Industry Request'), ('announcement', 'General Announcement'), ('guideline', 'UIL Guideline/Manual')], max_length=30)),
                ('content', models.TextField(help_text='The main body of the post')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_internal_only', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional: Post will be hidden after this date.', null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('request', 'assignment', 'user', 'industryprofile')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='bulletin_po_content_185660_idx')],
            },
        ),
    ]
